name: CorpRoutine
main: net.aerulion.corproutine.Main
version: '1.1'
author: aerulion
api-version: '1.16'
commands:
  routine:
    description: Oeffnet das Routine-Aufgaben-Menu
permissions:
  corproutine.use:
    default: op
  corproutine.alert:
    default: op