name: CorpRoutine
main: net.aerulion.corproutine.Main
version: ${project.version}
author: aerulion
api-version: '1.16'
depend: [ Nucleus ]
commands:
  routine:
    description: Oeffnet das Routine-Aufgaben-Menu
permissions:
  corproutine.use:
    default: op
  corproutine.alert:
    default: op